apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-deployment 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: hotel-deployment-container 
        image: YeongKing/hotel_prj:latest
        ports:
        - containerPort: 8080
